language: python
dist: trusty
sudo: false

matrix:
  include:
    - python: "3.5"

if: tag IS blank

before_script:
  - pip install --upgrade setuptools

install:
  - pip install coveralls
  - pip install bandit
  - pip install THD_Flow

script:
  - flow github version development
  - coverage run --source flow -m py.test
  #- bandit -r -ll -ii -x tests .

after_success:
  - coverage report
  - coveralls
